server:
  port: 8888

spring:
  application:
    name: Stock-CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/dscbmds/config-server-exampl.git 
          clone-on-start: true
